server:
  port: 8080
  shutdown: graceful

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/mem-data
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
  version: 0.0.1
  app-url: http://localhost:${server.port}
  app-description: Development URL
  app-title: Test Code


